version: "3.0"
services:
  iventoy:
    image: iventoy
    container_name: iventoy
    privileged: true
    volumes:
      - iso:/var/iventoy/iso
    ports:
      - 3067:67/udp
      - 3068:69/udp
      - 3069:69/udp
      - 26000:26000/tcp
      - 16000:16000/tcp
      - 10809:10809/tcp
    restart: unless-stopped
volumes:
  iso:
    external: true
